### PR TITLE
Benchmark with FDTD

### LINKED ISSUE #25: Benchmarks

### PR DESCRIPTION
**Pull request by foldfelis**
Close #25

### CODE REVIEW

**Comment by yuehhua** [comment]
May I join this work?

**Comment by foldfelis** [comment]
@yuehhua Please fork and PR back to the `bm` branch

**Comment by yuehhua** [comment]
Would you mind I refactor some types and methods in order to simplify the process?

**Comment by foldfelis** [comment]
any suggestion or advice is welcome

**Comment by yuehhua** [comment]
The encapsulation here is good and the whole simulation is crafted very well.
But the encapsulation seems the way too much, and I smell some sense of over-engineering.
Actually, `Bound` and `Discretizer` can be replaced by some constants and a `discretize` function, that should be enough.
What people say "encapsulate what varies" is this. We put things that vary into a type, and that is the parameters people want to tune with.
And the `RandPermittivity` seems a little bit odd here. It looks like a constructor, but it is more like a process that generates `Permittivity` in case of random. So, I make it like `Base.rand(::Type{Permittivity}, ...)`.
I believe that will get better.

**Comment by foldfelis** [comment]
1. The suggestion of `Permittivity` looks good to me. 
2. The point of `Bound` and `Discretizer` is that they are obviously sharing different meaning and are both tunable by user. One can reset one of them or both without construct new `Simulator`. BTW, please be aware of the `Δt` and `nt` in the `Discretizer`. They are bounded by a limitaion and may occur problem if breaking the limitation.

**Comment by yuehhua** [comment]
`Bound` and `Discretizer` are two good encapsulation here. The higher point of view here is "Do we actually need this encapsulation?" There are some considerations:

1. Do we need freedom at this point? We of course can make it tunable, but does user really need it? Or, can it be replaced by something simple? When user might need it? Thus, we can have further design.
2. Does it make sense without constructing a new `Simulator` but just adjusting its boundaries? Yeah, it is convenient but a little bit weird. I have a `Simulator` but I have different boundaries for different conditions.

**Comment by foldfelis** [comment]
I'll open another PR since the conversations are focused on the simulation but not benchmarking. And the simulation project is moved out of this project.

**Pull request closed without merging**
