### PR TITLE
Add julia version upper bound for CI

### PR DESCRIPTION
**Pull request by yuehhua**

### CODE REVIEW

**Comment by foldfelis** [comment]
@yuehhua  please add CI for Windows for me will you. Sorry I'm so busy lately...

**Comment by foldfelis** [comment]
BTW, just checking, did you find the solution to the type unstable problem [here](https://github.com/foldfelis/NeuralOperators.jl/blob/ad6b55ece88d4d476b2a9dbcb6db4973e6fa3a00/src/fourier.jl#L168) ?

**Comment by yuehhua** [comment]
> @yuehhua please add CI for Windows for me will you. Sorry I'm so busy lately...

Done.

> BTW, just checking, did you find the solution to the type unstable problem here ?

Not yet, I am currently working on implementing wavelet transform and its operators.

**Comment by foldfelis** [comment]
> Not yet, I am currently working on implementing wavelet transform and its operators.

any Ref ?

**Comment by yuehhua** [comment]
You can check #29.

**Pull request merged**
