### PR TITLE
Refactor

### LINKED ISSUE #28: Tullio is type unstable
[src](https://github.com/foldfelis/NeuralOperators.jl/blob/ad6b55ece88d4d476b2a9dbcb6db4973e6fa3a00/src/fourier.jl#L168)

Due to the type unstable proplem, the performance of FNO in julia implementation is limited.

### PR DESCRIPTION
**Pull request by yuehhua**
Closes #28

### CODE REVIEW

**Comment by yuehhua** [comment]
I reimplemented `apply_spectral_pattern` and got type unstable fixed.
This implementation let go of Tullio.jl and it works with cpu/gpu and their gradients.
It gets similar performance as Tullio.jl.

Benchmark with cpu array:

```julia
julia> @benchmark apply_spectral_pattern($A, $B)
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.561 μs … 794.284 μs  ┊ GC (min … max):  0.00% … 97.20%
 Time  (median):     1.717 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):   2.276 μs ±  12.270 μs  ┊ GC (mean ± σ):  11.07% ±  2.17%

  ▃█▇▆▅▃▁▁  ▁▁  ▁       ▁                                     ▁
  █████████████████████████▇█▇▇▇▇▇▆▇▆▇▇▅▅▆▆▆▇▆▆▅▅▅▅▅▆▅▃▅▅▄▄▅▆ █
  1.56 μs      Histogram: log(frequency) by time      5.64 μs <

 Memory estimate: 4.20 KiB, allocs estimate: 15.
```

Benchmark with CUDA array:

```julia
julia> @benchmark apply_spectral_pattern($A, $B)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):   7.829 μs …  1.625 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     22.419 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   21.750 μs ± 17.931 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

                       ▂▇█▇▅▅▇▅▅▆▅▅▅▄                          
  ▅▆▆▆▅▅▅▅▅▅▆▅▅▅▅▅▅▅▅▅▅██████████████▇▄▃▃▂▂▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ ▄
  7.83 μs         Histogram: frequency by time        41.8 μs <

 Memory estimate: 1.44 KiB, allocs estimate: 28.
```

**Comment by foldfelis** [comment]
> It gets similar performance as Tullio.jl.

Woo, that's disappointed... 

great work, though.

**Comment by yuehhua** [comment]
Sorry, I think I should benchmark it on larger arrays......

Use Tullio.jl:

```julia
julia> A = rand(300, 400, 50);

julia> B = rand(300, 400, 60);

julia> @benchmark NeuralOperators.apply_spectral_pattern($A, $B)
BenchmarkTools.Trial: 19 samples with 1 evaluation.
 Range (min … max):  260.968 ms … 271.714 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     264.138 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   264.660 ms ±   2.812 ms  ┊ GC (mean ± σ):  0.02% ± 0.07%

  ▁  ▁▁▁    ▁   ▁█ █▁  █▁  ▁    ▁       ▁              ▁      ▁  
  █▁▁███▁▁▁▁█▁▁▁██▁██▁▁██▁▁█▁▁▁▁█▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁█ ▁
  261 ms           Histogram: frequency by time          272 ms <

 Memory estimate: 6.87 MiB, allocs estimate: 10.

julia> A = cu(rand(300, 400, 50));

julia> B = cu(rand(300, 400, 60));

julia> @benchmark NeuralOperators.apply_spectral_pattern($A, $B)
BenchmarkTools.Trial: 1415 samples with 1 evaluation.
 Range (min … max):  21.625 μs …    5.029 s  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     48.138 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):    6.555 ms ± 172.461 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▆█▇▇▇▆▅▃                      ▂▂▂ ▁ ▁    ▁▁▁                 ▁
  █████████▆▆▅▆▁▁▁▁▁▁▁▁▁▁▁▁▁▆▆▇█████████▆▇▇████▆▇▅▆▇▇▄▁▆▇▅▄▁▄▄ █
  21.6 μs       Histogram: log(frequency) by time       416 μs <

 Memory estimate: 5.30 KiB, allocs estimate: 123.
```

Reimplemented:

```julia
julia> A = rand(300, 400, 50);

julia> B = rand(300, 400, 60);

julia> @benchmark NeuralOperators.apply_spectral_pattern($A, $B)
BenchmarkTools.Trial: 5 samples with 1 evaluation.
 Range (min … max):  1.061 s …   1.137 s  ┊ GC (min … max):  9.27% … 18.00%
 Time  (median):     1.102 s              ┊ GC (median):    11.12%
 Time  (mean ± σ):   1.101 s ± 33.396 ms  ┊ GC (mean ± σ):  11.02% ±  7.02%

  █         █                   █                     █   █  
  █▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█▁▁▁█ ▁
  1.06 s         Histogram: frequency by time        1.14 s <

 Memory estimate: 2.69 GiB, allocs estimate: 17.

julia> A = cu(rand(300, 400, 50));

julia> B = cu(rand(300, 400, 60));

julia> @benchmark NeuralOperators.apply_spectral_pattern($A, $B)
BenchmarkTools.Trial: 54 samples with 4 evaluations.
 Range (min … max):   7.213 μs … 26.032 ms  ┊ GC (min … max): 0.00% … 1.03%
 Time  (median):     25.976 ms              ┊ GC (median):    1.02%
 Time  (mean ± σ):   23.284 ms ±  7.357 ms  ┊ GC (mean ± σ):  1.04% ± 3.92%

                                                           ▃█  
  ▆▁▅▁▁▁▁▁▁▁▁▅▆▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅▁▁▁▁██ ▁
  7.21 μs      Histogram: log(frequency) by time        26 ms <

 Memory estimate: 1.25 KiB, allocs estimate: 24.
```

The results show large performance difference and Tullio.jl get best performance on either cpu or gpu.
Even though Tullio.jl has intrinsic type unstable issue, it still get best performance.
I think the type unstable issue comes from the package design itself and it is hard to avoid.

**Comment by foldfelis** [comment]
From my last check, yes, it is the fact. So what I meant is to fix the type unstable problem in Tullio.jl

**Comment by yuehhua** [comment]
It seems to be complicated. Tullio.jl use Cassette.jl to overdubbing the Julia code for CPU or CUDA. The `Core.Box` encapsulates codes under different context, instead of dispatching codes, which led to type unstable. It seems to be the core mechanism for Tullio.jl and could be hard to avoid it.

**Comment by yuehhua** [comment]
We have checked that even we removed type unstable, and it gains little performance improvement. Maybe we can rethink it as a key issue here.

**Comment by foldfelis** [comment]
I'm closing this PR since not much we can do about this.

**Pull request closed without merging**
