### PR TITLE
Deeponet

### LINKED ISSUE #37: Porting support for DeepONets from OperatorLearning.jl
This issue aims to add support for DeepONets (based on http://arxiv.org/abs/1910.03193) to the package

### PR DESCRIPTION
**Pull request by ba2tripleO**
Resolves #37. I have added the files for DeepONet implementation from OperatorLearning.jl and added tests for the architecture.

### CODE REVIEW

**Comment by ba2tripleO** [comment]
@foldfelis should I update the readme and docs as well?

**Comment by foldfelis** [comment]
Hi @Abhishek-1Bhatt it would be great to have the docs and readme updated 😊

**Comment by ba2tripleO** [comment]
Great 😊, I'll start working on it.

**Comment by foldfelis** [comment]
Hi @Abhishek-1Bhatt I didn't notice that there is a model training task inside the test 🤣 . I was wondering why the CI kept running for an hour. Is there another way to test DeepONet?

**Comment by ba2tripleO** [comment]
Oh😅, this was intended to be a regression test, just to sanity check that our model's training does not get deteriorated if we try out something new in the future. Indeed it doesn't make sense to train for 400 epochs here, I see that now : ) . One thing we can do is to reduce the no. of epochs to 100 or even lesser  and then check against the error bound or would you like to have a different way of testing for it? @ChrisRackauckas  might also have some suggestions regarding regression testing here.

**Comment by foldfelis** [comment]
Usually, I only do the unit test and put the training tasks into the example folder. I will manually test the examples locally to make sure that things won't go wrong. I am looking for a more efficient way to test the robustness of the models as well.

**Comment by ba2tripleO** [comment]
That seems like a nice way to do it, we can transfer it to example/Burgers

**Comment by foldfelis** [comment]
Feel free to add new examples and I will reorganize and refactor the project once the new featur is merged.

**Comment by ba2tripleO** [comment]
Removed an import of MAT.jl,  it was causing the tests to fail😅

**Comment by foldfelis** [comment]
Looks good to me 🎉

**Pull request merged**
